package java核心编程.static_learn;

import java.util.*;

public class Test111 {

    public static void main2(String[] args) {
        String languageKey = "app_name\n" +
                "app_title_left\n" +
                "app_title_sure\n" +
                "app_title_ok\n" +
                "app_title_good\n" +
                "app_few_error\n" +
                "app_view_all\n" +
                "app_title_yes\n" +
                "app_device_root\n" +
                "app_signature_true\n" +
                "main_page_book\n" +
                "main_page_dinning\n" +
                "main_page_reservation\n" +
                "main_page_account\n" +
                "main_page_more\n" +
                "main_page_vouchers\n" +
                "main_exit_app\n" +
                "main_law_text\n" +
                "main_law_agree\n" +
                "main_law_cancel\n" +
                "main_law_rich_terms\n" +
                "main_law_rich_privacy\n" +
                "main_law_rich_cookies\n" +
                "wecast_ssid_default_hotel\n" +
                "home_page_search\n" +
                "home_promotion_title\n" +
                "home_promotion_explian\n" +
                "home_promotion_clause\n" +
                "home_webview_title\n" +
                "home_notice_back\n" +
                "error_net_server\n" +
                "error_net_no\n" +
                "error_net_no_dialog_text\n" +
                "error_net_no_dialog_sure\n" +
                "error_net_no_dialog_cancel\n" +
                "error_net_unknown\n" +
                "error_net_login_expired\n" +
                "searchenter_page_btn\n" +
                "searchenter_page_special\n" +
                "searchenter_page_room\n" +
                "searchenter_page_rooms\n" +
                "searchenter_page_adult\n" +
                "searchenter_page_adults\n" +
                "searchenter_page_kid\n" +
                "searchenter_page_kids\n" +
                "searchenter_select_hotel\n" +
                "cp_hot_city\n" +
                "cp_hot_city_index\n" +
                "cp_recent_city\n" +
                "cp_recent_history\n" +
                "cp_located_city\n" +
                "cp_nothing_found\n" +
                "cp_locating\n" +
                "cp_located_failed\n" +
                "cp_located_cancel\n" +
                "calendar_day_format\n" +
                "calendar_button_sure\n" +
                "calendar_week_SUN\n" +
                "calendar_week_MON\n" +
                "calendar_week_TUE\n" +
                "calendar_week_WED\n" +
                "calendar_week_THU\n" +
                "calendar_week_FRI\n" +
                "calendar_week_SAT\n" +
                "calendar_text_startdate\n" +
                "calendar_text_enddate\n" +
                "calendar_text_check_out_date\n" +
                "calendar_title_name\n" +
                "calendar_choice_nights\n" +
                "calendar_choice_night\n" +
                "calendar_add_success\n" +
                "calendar_add_successed\n" +
                "calendar_permission_title\n" +
                "calendar_permission_yes\n" +
                "calendar_permission_no\n" +
                "app_permission_calendar\n" +
                "app_permission_location\n" +
                "app_permission_write_storage\n" +
                "app_permission_calendar_login\n" +
                "calendar_add_failed\n" +
                "calendar_max_ngiths\n" +
                "calendar_price_reference\n" +
                "rooms_title_name\n" +
                "rooms_button_sure\n" +
                "rooms_number_adults\n" +
                "rooms_number_children\n" +
                "rooms_text_explain\n" +
                "rooms_select_warn\n" +
                "rooms_add\n" +
                "rooms_max_explain\n" +
                "rooms_plan_dinner\n" +
                "rooms_fee_note\n" +
                "rooms_max_room_msg\n" +
                "rooms_child_max_age\n" +
                "special_title_name\n" +
                "special_text_rate\n" +
                "special_text_code\n" +
                "special_hind_code\n" +
                "special_text_type\n" +
                "special_text_corporate\n" +
                "special_text_goup\n" +
                "special_text_promotion\n" +
                "special_text_travel\n" +
                "special_business_travel_program\n" +
                "hotel_list_points\n" +
                "hotel_list_soldout\n" +
                "hotel_list_contact\n" +
                "detail_facility_dingding\n" +
                "detail_facility_gym\n" +
                "detail_facility_spa\n" +
                "detail_facility_prepay\n" +
                "detail_facility_more\n" +
                "detail_data_title\n" +
                "detail_data_features\n" +
                "detail_data_gcpoints\n" +
                "detail_data_redeem\n" +
                "detail_data_booking\n" +
                "detail_data_tel\n" +
                "detail_data_call\n" +
                "detail_data_email\n" +
                "detail_data_pernight\n" +
                "detail_data_intro\n" +
                "detail_data_points\n" +
                "detail_data_points_des\n" +
                "detail_data_residuerooms\n" +
                "detail_data_residueroom\n" +
                "detail_data_norooms\n" +
                "detail_data_copy\n" +
                "detail_booking_sure\n" +
                "detail_booking_cancel\n" +
                "detail_booking_ok\n" +
                "detail_booking_copyemail\n" +
                "detail_cash_points\n" +
                "detail_member_rate\n" +
                "gallery_title_name\n" +
                "gallery_title_all\n" +
                "periphery_title_text\n" +
                "periphery_indicator_traffic\n" +
                "periphery_indicator_attraction\n" +
                "periphery_indicator_shopping\n" +
                "periphery_indicator_entertain\n" +
                "periphery_marker_nodata\n" +
                "periphery_btn_navigation\n" +
                "periphery_navigation_no\n" +
                "periphery_maps_a\n" +
                "periphery_maps_baidu\n" +
                "periphery_maps_google\n" +
                "pull_to_refresh_pull_label\n" +
                "pull_to_refresh_release_label\n" +
                "pull_to_refresh_refreshing_label\n" +
                "pull_to_refresh_load_more_label\n" +
                "app_refresh_retry\n" +
                "srl_header_pulling\n" +
                "srl_header_release\n" +
                "srl_header_refreshing\n" +
                "srl_header_finish\n" +
                "srl_header_failed\n" +
                "srl_header_update\n" +
                "srl_header_loading\n" +
                "srl_footer_pulling\n" +
                "srl_footer_release\n" +
                "srl_footer_loading\n" +
                "srl_footer_finish\n" +
                "srl_footer_failed\n" +
                "srl_footer_refreshing\n" +
                "srl_footer_nothing\n" +
                "title_settings_dialog\n" +
                "dialog_order_delete_describe\n" +
                "dialog_order_cancel_point_upgrade_title\n" +
                "dialog_order_cancel_point_upgrade_policy_title\n" +
                "dialog_order_cancel_point_extend_stay_title\n" +
                "dialog_order_cancel_point_extend_stay_policy_title\n" +
                "dialog_order_cancel_btn\n" +
                "dialog_order_confirm_btn\n" +
                "dialog_order_cancel_denny_btn\n" +
                "dialog_order_cancel_confirm_btn\n" +
                "dialog_order_describ_search_number_error\n" +
                "dialog_order_describ_search_name_error\n" +
                "dialog_order_describ_search_cancel_success\n" +
                "dialog_order_refund_coupon\n" +
                "order_item_tips_info\n" +
                "order_item_reservation_room_number\n" +
                "night\n" +
                "nights\n" +
                "booking_again\n" +
                "redeem_again\n" +
                "cancel\n" +
                "invoice\n" +
                "delete\n" +
                "check_in\n" +
                "check_out\n" +
                "title_find_room_reservation_\n" +
                "hint_confirmation_number_\n" +
                "hint_last_name_\n" +
                "order_tips_login_\n" +
                "order_tips_login_vouchers\n" +
                "order_tips_login_spannable\n" +
                "order_tips_no_stays_\n" +
                "order_tips_no_stays_spannable\n" +
                "order_tips_no_vouchers_\n" +
                "order_tips_no_vouchers_spannable\n" +
                "order_tips_login_coupon\n" +
                "order_tips_no_coupon\n" +
                "order_tips_all_no_reservation\n" +
                "order_list_title_\n" +
                "order_list_tab_upcoming_stays_\n" +
                "order_list_tab_all_stays_\n" +
                "order_list_search_reservation_\n" +
                "order_list_cancellation_number_\n" +
                "order_list_confirmation_number_\n" +
                "order_list_confirmation_voucher_\n" +
                "order_list_cancel_alert_title\n" +
                "order_list_cancel_alert_reason\n" +
                "order_list_cancel_alert_ok\n" +
                "order_list_points_redeem\n" +
                "order_list_room_upgrade\n" +
                "order_list_extend_stay\n" +
                "order_list_points_cash\n" +
                "order_list_points\n" +
                "order_list_search_error_name\n" +
                "order_list_search_poly_phone\n" +
                "order_list_search_wrong_name\n" +
                "order_list_date_expiry\n" +
                "order_cancel_no_confirmation_number\n" +
                "order_list_coupon_id\n" +
                "order_list_coupon_refund\n" +
                "order_list_coupon_date\n" +
                "order_list_coupon_confirm\n" +
                "order_list_coupon_cancel\n" +
                "order_list_pay_now\n" +
                "order_list_cancel_pay\n" +
                "order_list_to_be_paid\n" +
                "order_list_cancel_pay_tips\n" +
                "order_list_pay_succeeded_tips\n" +
                "order_list_pay_overtime_tips\n" +
                "voucher_detail_title_restaurant\n" +
                "voucher_detail_title_spa\n" +
                "voucher_detail_reference_no\n" +
                "voucher_detail_gc_award_points_redeemed\n" +
                "voucher_detail_redemption_detail_title\n" +
                "voucher_detail_information_title\n" +
                "voucher_detail_vouchers\n" +
                "voucher_detail_expiry_date\n" +
                "voucher_detail_cancellation_policy_title\n" +
                "voucher_detail_personal_information_title\n" +
                "login_security_dialog_ok\n" +
                "login_register_booknow\n" +
                "login_register_\n" +
                "login_register_tips_\n" +
                "login_hint_member_id_\n" +
                "login_hint_pass_\n" +
                "login_wrong_pass_tips_\n" +
                "login_wrong_pass_tip_\n" +
                "login_forget_pass_\n" +
                "login_button_text_\n" +
                "login_active_account_\n" +
                "login_null_user\n" +
                "login_null_pass\n" +
                "login_error_banned\n" +
                "login_null_username\n" +
                "login_enhance_account_security\n" +
                "login_enhance_security_content\n" +
                "sign_by_phone\n" +
                "sign_by_email\n" +
                "login_hint_phone\n" +
                "login_area_code_error\n" +
                "login_tab_member\n" +
                "login_tab_mobile\n" +
                "login_join\n" +
                "login_change_to_code\n" +
                "login_change_to_pw\n" +
                "login_dialog_phone\n" +
                "login_dialog_email\n" +
                "login_forget_pw\n" +
                "login_google_failed\n" +
                "login_hint_code\n" +
                "login_email\n" +
                "login_email_valid\n" +
                "login_local_phone\n" +
                "login_agree\n" +
                "login_one_key\n" +
                "login_other_register\n" +
                "login_warning\n" +
                "login_token_failed\n" +
                "account_title_text\n" +
                "account_transaction_history\n" +
                "account_redemeption_group\n" +
                "account_my_profile\n" +
                "account_member_benefits\n" +
                "account_account_settings\n" +
                "account_sing_out\n" +
                "account_redeem\n" +
                "account_points_balance\n" +
                "account_gold\n" +
                "account_jade\n" +
                "account_diamond\n" +
                "account_gold_level\n" +
                "account_jade_level\n" +
                "account_diamond_level\n" +
                "account_polaris_level\n" +
                "account_night\n" +
                "account_stay\n" +
                "account_login_register\n" +
                "account_night_gold_start\n" +
                "account_night_gold_middle\n" +
                "account_night_jade_middle\n" +
                "account_night_polaris\n" +
                "account_tier_gold_start\n" +
                "account_tier_gold_middle\n" +
                "account_tier_jade_middle\n" +
                "account_tier_polaris\n" +
                "account_refresh_title\n" +
                "account_refresh_day\n" +
                "account_refresh_days\n" +
                "account_title_thanks\n" +
                "account_setting_title\n" +
                "account_setting_pw\n" +
                "account_setting_pw_init\n" +
                "account_setting_pw_not\n" +
                "account_setting_like_title\n" +
                "account_setting_like_save\n" +
                "account_setting_like_language\n" +
                "account_setting_like_dialog\n" +
                "account_setting_like_change_success\n" +
                "account_uplevel_des\n" +
                "account_uplevel_gonew\n" +
                "account_uplevel_congratulatio\n" +
                "account_logout_toast\n" +
                "account_upgrade_jade_nights\n" +
                "account_upgrade_jade_stays\n" +
                "account_upgrade_diamond_nights\n" +
                "account_upgrade_diamond_stays\n" +
                "account_upgrade_rollorver\n" +
                "account_points_unit\n" +
                "account_member_tier\n" +
                "account_member_since\n" +
                "account_member_valid\n" +
                "account_benefits_all\n" +
                "account_member_refresh\n" +
                "account_member_refresh_hint\n" +
                "account_setting_email\n" +
                "account_setting_email_hint\n" +
                "account_setting_email_pw_hint\n" +
                "account_setting_email_button\n" +
                "account_setting_email_explain\n" +
                "account_setting_email_modify\n" +
                "account_setting_email_verify\n" +
                "account_setting_email_modify_submit\n" +
                "account_setting_email_password_empty\n" +
                "account_setting_email_password_usedover\n" +
                "account_setting_email_modify_hint\n" +
                "account_setting_email_input_hint\n" +
                "account_setting_email_input_error\n" +
                "account_setting_email_input_different\n" +
                "account_setting_email_input_modifywarn\n" +
                "account_setting_email_top_tip\n" +
                "account_setting_email_modify_tip\n" +
                "account_setting_email_no_receive\n" +
                "account_setting_bind_success\n" +
                "account_setting_unbind_success\n" +
                "account_setting_mobile\n" +
                "account_setting_wechat\n" +
                "wechat_unbind_title\n" +
                "wechat_unbind_message\n" +
                "account_setting_wechat_bind\n" +
                "account_setting_wechat_unbind\n" +
                "account_setting_wechat_unbind_item\n" +
                "account_setting_mobile_tips\n" +
                "account_setting_mobile_title_add\n" +
                "account_setting_mobile_title_verify\n" +
                "account_setting_mobile_title_modify\n" +
                "account_setting_mobile_tips_bottom\n" +
                "account_setting_mobile_no_receive\n" +
                "account_setting_mobile_diff_phone\n" +
                "account_setting_not_pwd_warning\n" +
                "account_setting_google\n" +
                "google_unbind_title\n" +
                "google_unbind_desc\n" +
                "google_unbind_unlink\n" +
                "mobile_phone_top_tip\n" +
                "mobile_phone_modify_tip\n" +
                "mobile_phone_area_error\n" +
                "account_setting_go_to_add\n" +
                "account_setting_verify_login_email\n" +
                "account_setting_verify_login_phone\n" +
                "account_verify_input_dialog_msg\n" +
                "account_verify_alert_dialog_skip\n" +
                "account_verify_alert_dialog_skip_one\n" +
                "account_verify_alert_dialog_msg\n" +
                "account_verify_alert_dialog_phone\n" +
                "account_verify_alert_dialog_phone_update\n" +
                "account_verify_alert_dialog_email\n" +
                "account_verify_alert_dialog_tip\n" +
                "account_setting_bind_confirm\n" +
                "fastcheck_title_text\n" +
                "fastcheck_reservation_details\n" +
                "fastcheck_onlin\n" +
                "fastcheck_hotel_detail\n" +
                "fastcheck_map\n" +
                "fastcheck_taxi_helper\n" +
                "fastcheck_call\n" +
                "fastcheck_email\n" +
                "fastcheck_feedback\n" +
                "fastcheck_local_weather\n" +
                "fastcheck_local_time\n" +
                "fastcheck_add_calendar\n" +
                "fastcheck_enjoy\n" +
                "fastcheck_points_text\n" +
                "fastcheck_points\n" +
                "fast_check_in_room_number\n" +
                "fastcheck_calendar_reservation\n" +
                "fastcheck_smart_room\n" +
                "fast_checkout_title\n" +
                "fast_checkout_my_service\n" +
                "fast_checkout_folio\n" +
                "redeem_point_title\n" +
                "redeem_text\n" +
                "redeem_point_available\n" +
                "redeem_point_login\n" +
                "item_title_room_awards\n" +
                "item_title_room_upgrade_awards\n" +
                "item_title_no_room_awards\n" +
                "item_title_life_awards\n" +
                "item_title_points_miles\n" +
                "item_describe_room_awards\n" +
                "item_describe_room_upgrade_awards\n" +
                "item_describe_no_room_awards\n" +
                "item_describe_life_awards\n" +
                "item_describe_points_miles\n" +
                "transaction_history_title\n" +
                "transaction_non_history\n" +
                "transaction_history_filter_3\n" +
                "transaction_history_filter_24\n" +
                "redeem_search_title\n" +
                "nonroom_title_text\n" +
                "nonroom_dining\n" +
                "nonroom_spa\n" +
                "nonroom_points\n" +
                "nonroom_how_to\n" +
                "nonroom_type_vouchers\n" +
                "nonroom_rooms_number\n" +
                "nonroom_points_number\n" +
                "nonroom_btn_next\n" +
                "nonroom_points_enough\n" +
                "nonroom_nonsupport_text\n" +
                "nonroom_search_hint\n" +
                "nonroom_search_toast\n" +
                "room_awards_title\n" +
                "room_awards_points_only_title\n" +
                "room_awards_extend_stay_title\n" +
                "room_awards_points_only_content\n" +
                "room_awards_extend_stay_content\n" +
                "redemption_award_chart\n" +
                "room_awards_extend_stay_empty\n" +
                "room_upgrade_chart\n" +
                "points_miles_main_title\n" +
                "points_miles_main_Table\n" +
                "points_miles_main_programme\n" +
                "points_miles_main_award\n" +
                "points_miles_main_equivalent\n" +
                "points_miles_main_cancellation\n" +
                "points_miles_main_special_offer\n" +
                "points_miles_main_law_spannable\n" +
                "points_miles_main_law\n" +
                "points_miles_continue\n" +
                "points_miles_cancel\n" +
                "points_miles_points_unit\n" +
                "points_miles_points_errortoast\n" +
                "points_miles_points_password_title\n" +
                "points_miles_points_law_check\n" +
                "points_miles_points_flyererror\n" +
                "points_miles_points_redeemnow\n" +
                "arline_select_title\n" +
                "arline_select_edit\n" +
                "arline_select_add\n" +
                "arline_select_empty\n" +
                "redeem_miles_success_submitted\n" +
                "redeem_miles_success_details\n" +
                "redeem_miles_success_otherdaress\n" +
                "redeem_miles_success_sendemail\n" +
                "redeem_miles_success_done\n" +
                "redeem_miles_success_sendemail_label\n" +
                "redeem_miles_success_email_errortoast\n" +
                "message_box_title\n" +
                "message_box_read_all\n" +
                "message_box_empty\n" +
                "message_detail_title\n" +
                "select\n" +
                "go_new\n" +
                "language\n" +
                "currency\n" +
                "clean_cache\n" +
                "notification\n" +
                "notification_des\n" +
                "notification_close_tips\n" +
                "contact_us\n" +
                "feedback\n" +
                "terms\n" +
                "privacy\n" +
                "clean_cache_complete\n" +
                "notification_not_open\n" +
                "about\n" +
                "about_version\n" +
                "about_rate\n" +
                "about_not_found\n" +
                "allow_recommend\n" +
                "allow_recommend_desc\n" +
                "more_cookies_policy\n" +
                "more_currency\n" +
                "more_language\n" +
                "more_language_now\n" +
                "more_language_chinese\n" +
                "more_language_english\n" +
                "more_language_Japanese\n" +
                "more_screen_cast\n" +
                "more_location_alert_title\n" +
                "more_location_alert_content\n" +
                "more_location_alert_sure\n" +
                "more_location_alert_cancel\n" +
                "order_search_empty_number\n" +
                "order_search_empty_name\n" +
                "credit_card_list_title\n" +
                "credit_card_list_empty\n" +
                "credit_card_list_add\n" +
                "credit_card_list_expired\n" +
                "credit_card_list_default\n" +
                "credit_card_list_full\n" +
                "credit_card_editor_title\n" +
                "credit_card_editor_policy\n" +
                "credit_card_editor_set_default\n" +
                "save\n" +
                "credit_card_editor_already_default\n" +
                "credit_card_add_title\n" +
                "credit_card_add_policy_head\n" +
                "credit_card_add_policy_save\n" +
                "credit_card_add_policy_save_desc\n" +
                "credit_card_add_policy_full\n" +
                "credit_card_add_delete_alert\n" +
                "hint_credit_card_add_type\n" +
                "hint_credit_card_add_number\n" +
                "hint_credit_card_add_user\n" +
                "hint_credit_card_add_expire_date\n" +
                "confirm\n" +
                "credit_card_add_expired_alert\n" +
                "credit_card_add_null_card_type\n" +
                "credit_card_add_null_card_number\n" +
                "credit_card_add_null_card_user\n" +
                "credit_card_add_null_card_expired\n" +
                "credit_card_add_null_card_type_tips\n" +
                "credit_card_add_null_card_number_tips\n" +
                "credit_card_add_null_card_expired_tips\n" +
                "credit_card_confirm\n" +
                "credit_card_cancel\n" +
                "ok\n" +
                "OK\n" +
                "hotel_detail_yellow_tip_confirm\n" +
                "credit_card_add_check_box_tips\n" +
                "month\n" +
                "year\n" +
                "yes\n" +
                "deny\n" +
                "hot_country\n" +
                "guide_ui_skip\n" +
                "guide_ui_btn\n" +
                "upgrade_title\n" +
                "stfErrorMessage\n" +
                "stfOfflineMessage\n" +
                "stfLocationOffMessage\n" +
                "stfEmptyMessage\n" +
                "stfLoadingMessage\n" +
                "stfButtonText\n" +
                "noti_channel_default\n" +
                "noti_channel_second\n" +
                "noti_content_title\n" +
                "noti_content_text\n" +
                "noti_close\n" +
                "vercode_title\n" +
                "vercode_edithint\n" +
                "vercode_null\n" +
                "vercode_noresponding\n" +
                "vercode_neterror\n" +
                "flyerMemberlist_title\n" +
                "flyerMemberlist_item_edtior\n" +
                "flyerMemberlist_btn_add\n" +
                "flyerMemberlist_no_memberships\n" +
                "flyerMemberlist_title_member\n" +
                "add_fiyerMenbership_title\n" +
                "edit_fiyerMenbership_title\n" +
                "add_fiyerMenbership_reminder\n" +
                "add_fiyerMenbership_number\n" +
                "fiyerMenbership_error_code\n" +
                "fiyerMenbership_null_membership\n" +
                "fiyerMenbership_null_code\n" +
                "add_fiyerMenbership_save\n" +
                "add_fiyerMenbership_edit\n" +
                "add_fiyerMenbership_saved\n" +
                "share_wechat\n" +
                "share_facebook\n" +
                "share_moments\n" +
                "share_more\n" +
                "share_copy_link\n" +
                "share_copy_link_success\n" +
                "share_copy_link_fail\n" +
                "share_unfind\n" +
                "poster_generate\n" +
                "poster_product\n" +
                "poster_save_picture\n" +
                "poster_share_wechat\n" +
                "poster_share_moments\n" +
                "poster_save_sucess\n" +
                "poster_save_fail\n" +
                "poster_applicable_hotel_count\n" +
                "poster_qr_code_tips\n" +
                "poster_dlp_qr_code_tips\n" +
                "poster_image_load_fail_tips\n" +
                "register_gc_title\n" +
                "register_input_appellation\n" +
                "register_input_surname\n" +
                "register_input_first_name\n" +
                "register_date_of_birth\n" +
                "register_input_email\n" +
                "register_country\n" +
                "register_input_mobile\n" +
                "register_idd_code\n" +
                "register_gc_tips_1\n" +
                "register_gc_tips_2\n" +
                "register_gc_null_appellation_tips\n" +
                "register_gc_null_form_tips\n" +
                "register_gc_null_birthday_tips\n" +
                "register_gc_null_email_tips\n" +
                "register_gc_null_country_tips\n" +
                "register_gc_null_mobile_tips\n" +
                "register_next_step\n" +
                "register_phone_hint\n" +
                "register_email_hint\n" +
                "register_verify_title_phone\n" +
                "register_verify_title_email\n" +
                "register_verify_send_tips\n" +
                "register_verify_send\n" +
                "register_verify_verification_code\n" +
                "register_verify_not_received\n" +
                "register_verify_not_resend\n" +
                "register_verify_second\n" +
                "register_verify_error\n" +
                "register_verify_signin\n" +
                "register_verify_back\n" +
                "register_verify_dialog_phone\n" +
                "register_verify_dialog_email\n" +
                "legic_bluetooth_title\n" +
                "legic_bluetooth_request_key\n" +
                "legic_bluetooth_roomno\n" +
                "legic_bluetooth_law_terms\n" +
                "legic_bluetooth_law\n" +
                "legic_bluetooth_loading1\n" +
                "legic_bluetooth_loading2\n" +
                "legic_bluetooth_loading3\n" +
                "legic_bluetooth_loading4\n" +
                "legic_bluetooth_loading5\n" +
                "legic_bluetooth_success_explain\n" +
                "legic_bluetooth_success_right\n" +
                "legic_bluetooth_success_ok\n" +
                "legic_bluetooth_checked_contact\n" +
                "legic_bluetooth_law_warning\n" +
                "legic_sdkregister_failed_title\n" +
                "legic_sdkregister_failed_right\n" +
                "legic_sdkregister_failed_left\n" +
                "legic_opendoor_failed_title\n" +
                "legic_opendoor_failed_explain\n" +
                "legic_opendoor_wrong_explain\n" +
                "legic_opendoor_failed_noused\n" +
                "legic_opendoor_loading_hint\n" +
                "legic_opendoor_finish_hint\n" +
                "legic_opendoor_nokey\n" +
                "legic_guide_step1\n" +
                "legic_guide_step2\n" +
                "legic_guide_step3\n" +
                "legic_guide_next\n" +
                "legic_roomno_changed\n" +
                "curtain\n" +
                "conditioner\n" +
                "wind_speed\n" +
                "smart_device_mode\n" +
                "smart_device_light\n" +
                "smart_device_switch\n" +
                "smart_device_set_temperature\n" +
                "smart_device_wait_moment\n" +
                "smart_device_all_on\n" +
                "smart_device_all_off\n" +
                "smart_device_curtain\n" +
                "smart_device_sheer_curtain\n" +
                "smart_device_change_policy\n" +
                "smart_device_off\n" +
                "smart_device_on\n" +
                "smart_device_light_on\n" +
                "smart_device_light_off\n" +
                "error_113\n" +
                "error_117\n" +
                "error_122\n" +
                "error_123\n" +
                "error_127\n" +
                "error_128\n" +
                "error_129\n" +
                "error_134\n" +
                "error_135\n" +
                "error_136\n" +
                "error_137\n" +
                "error_141\n" +
                "error_149\n" +
                "error_150\n" +
                "error_152\n" +
                "error_154\n" +
                "error_178\n" +
                "error_255\n" +
                "ble_status_msg\n" +
                "allonline_success_title\n" +
                "allonline_permission_location_hint\n" +
                "allonline_permission_location_again\n" +
                "allonline_permission_allow\n" +
                "allonline_permission_reject\n" +
                "allonline_location_failed\n" +
                "allonline_success_head_cash\n" +
                "allonline_success_head_cash_find\n" +
                "allonline_success_foot_arrive\n" +
                "allonline_success_foot_special\n" +
                "allonline_success_foot_special_explain\n" +
                "allonline_dialog_confim\n" +
                "allonline_dialog_sure\n" +
                "allonline_dialog_cancle\n" +
                "allonline_dialog_agree\n" +
                "allonline_dialog_agree_not\n" +
                "allonline_dialog_try\n" +
                "allonline_dialog_again\n" +
                "allonline_dialog_verify_law\n" +
                "allonline_dialog_verify_title\n" +
                "allonline_dialog_verify_title_failed\n" +
                "allonline_bill_preAuth\n" +
                "allonline_bill_room\n" +
                "allonline_bill_incidental\n" +
                "allonline_bill_pay\n" +
                "allonline_eid_error\n" +
                "allonline_no_wechat_warn\n" +
                "chatbot_service_name\n" +
                "chatbot_service_enter\n" +
                "app_login_invalid\n" +
                "activate_mobile_title\n" +
                "activate_mobile_desc\n" +
                "activate_mobile_number\n" +
                "activate_mobile_restart_explain\n" +
                "activate_by_email\n" +
                "activate_number_empty\n" +
                "register_phone_empty\n" +
                "activate_go_login\n" +
                "activate_mobile_submit\n" +
                "my_voucher_title\n" +
                "my_voucher_valid\n" +
                "my_voucher_invalid\n" +
                "my_voucher_id\n" +
                "my_voucher_validity\n" +
                "my_voucher_empty\n" +
                "free_voucher_title\n" +
                "free_voucher_refund\n" +
                "free_voucher_bar_title\n" +
                "free_voucher_expired\n" +
                "free_voucher_hotel\n" +
                "free_voucher_relation\n" +
                "free_voucher_view_applicable_hotels\n" +
                "voucher_redeem_now\n" +
                "voucher_redeem_content\n" +
                "search_hotel_title\n" +
                "search_hotel_find\n" +
                "select_calendar_title\n" +
                "select_person_title\n" +
                "quick_with_join\n" +
                "quick_enjoy\n" +
                "quick_login_other\n" +
                "quick_login_other_back\n" +
                "quick_login_we_chat\n" +
                "quick_login_phone\n" +
                "quick_with_other\n" +
                "quick_with_register\n" +
                "quick_explain\n" +
                "quick_explain_click\n" +
                "quick_pw_tip\n" +
                "quick_preference\n" +
                "quick_family\n" +
                "quick_name\n" +
                "quick_password\n" +
                "quick_receive_phone\n" +
                "quick_receive_email\n" +
                "quick_preferred_title\n" +
                "quick_register_law\n" +
                "quick_law_terms\n" +
                "quick_law_privacy\n" +
                "quick_law_cookies\n" +
                "quick_register_success\n" +
                "quick_register_welcome\n" +
                "quick_register_number\n" +
                "quick_register_explain\n" +
                "quick_register_gender\n" +
                "quick_register_select\n" +
                "quick_register_keep\n" +
                "we_chat_auth_failed\n" +
                "level_upgrade_jade_diamond_title\n" +
                "level_upgrade_polaris_title\n" +
                "level_upgrade_jade_content\n" +
                "level_upgrade_diamond_content\n" +
                "level_upgrade_polaris_content\n" +
                "order_all_all\n" +
                "order_all_pending\n" +
                "order_all_upcoming\n" +
                "order_all_completed\n" +
                "order_empty_logout\n" +
                "order_empty_data\n" +
                "order_empty_data_up\n" +
                "order_add\n" +
                "search_order_title\n" +
                "upcoming_page_title\n" +
                "upcoming_order_detail\n" +
                "upcoming_facility_title\n" +
                "upcoming_stay_preference\n" +
                "upcoming_service_request\n" +
                "upcoming_laundry\n" +
                "upcoming_room_make_up\n" +
                "upcoming_baggage\n" +
                "voucher_guess_you_like\n" +
                "voucher_view_all_vouchers\n" +
                "voucher_login\n" +
                "voucher_tip_login\n" +
                "voucher_no_voucher_tip\n" +
                "voucher_shop\n" +
                "recommend_offers_title\n" +
                "recommend_destination_title\n" +
                "recommend_offer_price_pre\n" +
                "home_next_discover\n" +
                "home_entry_stay\n" +
                "home_entry_dine\n" +
                "home_entry_shop\n" +
                "home_discover_title\n" +
                "home_offer_from\n" +
                "home_offer_from_nights\n" +
                "pci_pwd_length_later_tip\n" +
                "pci_pwd_length_dont_tip\n" +
                "voucher_cross\n" +
                "delete_gc_title\n" +
                "delete_gc_caution\n" +
                "delete_gc_explain_title\n" +
                "delete_gc_sure\n" +
                "delete_gc_think\n" +
                "deleted_gc_submitted\n" +
                "delete_gc_know\n" +
                "delete_gc_warning\n" +
                "voucher_get_entrance\n" +
                "gifting_to_friends\n" +
                "gifting_to_friends_dialog_title\n" +
                "gifting_to_friends_dialog_content\n" +
                "gifting_to_friends_dialog_confirm\n" +
                "gifting_to_friends_dialog_cancel\n" +
                "gifting_support\n" +
                "gifting_cancel_dialog_title\n" +
                "gifting_cancel_dialog_content\n" +
                "gifting_cancel\n" +
                "gifting_cancel_close_window\n" +
                "gifting_select_wishes_title\n" +
                "gifting_agree_protocol\n" +
                "gifting_protocol\n" +
                "gifting_agree_protocol_tips\n" +
                "gifting_now_button_text\n" +
                "gifting_protocol_title\n" +
                "gifting_transfer_mini_program_title\n" +
                "gifting_tips\n" +
                "invoice_reapply_tip\n" +
                "invoice_apply\n" +
                "invoice_check_detail\n" +
                "invoice_status_changed\n" +
                "invoice_dialog_confirm\n" +
                "invoice_dialog_cancel\n" +
                "invoice_refund_tip_ok\n" +
                "invoice_fill_title\n" +
                "invoice_amount\n" +
                "invoice_type\n" +
                "invoice_type_vat\n" +
                "invoice_type_e_vat\n" +
                "invoice_title_type\n" +
                "invoice_title_type_enterprise\n" +
                "invoice_title_type_personal\n" +
                "invoice_title\n" +
                "invoice_company_tax_id\n" +
                "invoice_taxpayer_id\n" +
                "invoice_content\n" +
                "invoice_prepay_voucher\n" +
                "invoice_receive_email\n" +
                "invoice_submit_application\n" +
                "invoice_title_enterprise_hint\n" +
                "invoice_title_personal_hint\n" +
                "invoice_email_format_error\n" +
                "invoice_fill_single_voucher_tip\n" +
                "invoice_fill_cross_voucher_tip\n" +
                "invoice_reapply_title\n" +
                "invoice_apply_tip_dialog_content\n" +
                "invoice_receiver_info\n" +
                "invoice_receiver_name\n" +
                "invoice_receiver_name_hint\n" +
                "invoice_receiver_phone\n" +
                "invoice_receiver_phone_hint\n" +
                "invoice_receiver_email_hint\n" +
                "invoice_receiver_address\n" +
                "invoice_receiver_address_hint\n" +
                "invoice_please_input_receiver_phone\n" +
                "invoice_please_input_receiver_email\n" +
                "invoice_please_input_receiver_address\n" +
                "invoice_please_input_right_name\n" +
                "invoice_please_input_right_address\n" +
                "invoice_submit_success\n" +
                "invoice_submit_success_tip\n" +
                "invoice_back_to_voucher\n" +
                "invoice_detail_title\n" +
                "invoice_detail_title_name\n" +
                "invoice_detail_post_way\n" +
                "invoice_detail_post_way_delivery\n" +
                "invoice_detail_post_way_email\n" +
                "invoice_detail_express_company\n" +
                "invoice_detail_express_id\n" +
                "invoice_detail_post_address\n" +
                "invoice_status\n" +
                "invoice_reapply\n" +
                "invoice_resend\n" +
                "invoice_check\n" +
                "invoice_cannot_reapply\n" +
                "invoice_submit\n" +
                "invoice_email_send_success_tip\n" +
                "dialog_btn_i_know\n" +
                "chat_online\n" +
                "nominee_adult_relation\n" +
                "nominee_relation_warning\n" +
                "nominee_type\n" +
                "nominee_type_adult\n" +
                "nominee_type_child\n" +
                "nominee_status\n" +
                "nominee_phone_title\n" +
                "nominee_email_title\n" +
                "nominee_delete_tips\n" +
                "nominee_add\n" +
                "nominee_manage\n" +
                "nominee_benefits\n" +
                "nominee_max\n" +
                "nominee_status_active\n" +
                "nominee_status_incomplete\n" +
                "nominee_status_invited\n" +
                "nominee_status_review\n" +
                "nominee_complete_profile\n" +
                "nominee_add_title\n" +
                "nominee_add_adult\n" +
                "nominee_add_child\n" +
                "nominee_add_quota\n" +
                "nominee_add_is_gc\n" +
                "nominee_add_gc\n" +
                "nominee_add_gc_invalid\n" +
                "nominee_add_family_name\n" +
                "nominee_add_birth_invalid\n" +
                "nominee_add_invitation\n" +
                "nominee_add_law_adult\n" +
                "nominee_add_law_child\n" +
                "nominee_add_confirm_invite\n" +
                "nominee_add_confirm\n" +
                "nominee_add_law_invalid\n" +
                "nominee_add_contact_invalid\n" +
                "nominee_add_success_title\n" +
                "nominee_add_success_desc\n" +
                "nominee_edit_title\n" +
                "nominee_edit_explain\n" +
                "nominee_edit_contact\n" +
                "nominee_edit_provide\n" +
                "family_list_title\n" +
                "family_redeem_title\n" +
                "family_list_benefits\n" +
                "family_list_max\n" +
                "family_select_member\n" +
                "family_select_nominees\n" +
                "family_send_title\n" +
                "family_send_preferred\n" +
                "family_send_phone\n" +
                "family_send_email\n" +
                "family_send_invite\n" +
                "family_send_edit\n" +
                "family_send_delete\n" +
                "family_send_success_title\n" +
                "family_send_failed_title\n" +
                "family_send_success_desc\n" +
                "family_send_failed_desc\n" +
                "family_send_no_contact\n" +
                "family_empty\n" +
                "family_select_empty\n" +
                "score_title_order\n" +
                "score_title_co\n" +
                "score_title_coupon\n" +
                "score_desc\n" +
                "score_up\n" +
                "score_middle\n" +
                "score_down\n" +
                "shortcut_search\n" +
                "shortcut_order\n" +
                "shortcut_voucher\n" +
                "shortcut_account\n" +
                "app_save_image\n" +
                "app_save_success\n" +
                "app_save_failed\n" +
                "permission_location_title\n" +
                "permission_location_tips\n" +
                "bind_consolidate\n" +
                "bind_tab_hotel\n" +
                "bind_tab_confirm\n" +
                "bind_hint_hotel_name\n" +
                "bind_hint_check_date\n" +
                "bind_empty_name\n" +
                "bind_empty_date\n" +
                "bind_empty_confirm\n" +
                "bind_btn_find\n" +
                "bind_list_all\n" +
                "bind_order_success\n" +
                "bind_list_law\n" +
                "bind_list_law_warning\n" +
                "hotel_name_title\n" +
                "cbs_list_title\n" +
                "cbs_list_add\n" +
                "cbs_list_email\n" +
                "cbs_list_expire\n" +
                "cbs_list_link\n" +
                "cbs_list_active\n" +
                "cbs_list_empty\n" +
                "cbs_delete_title\n" +
                "cbs_delete_desc\n" +
                "cbs_delete_confirm\n" +
                "cbs_delete_cancel\n" +
                "cbs_add_title\n" +
                "cbs_add_title_active\n" +
                "cbs_add_desc\n" +
                "cbs_link_desc\n" +
                "cbs_add_email_warning\n" +
                "cbs_add_code\n" +
                "cbs_add_code_warning\n" +
                "cbs_add_not_code\n" +
                "cbs_add_not_desc\n" +
                "cbs_add_submit";
        String languageValue = "香格里拉會\n" +
                "取消\n" +
                "確定\n" +
                "確定\n" +
                "好的\n" +
                "操作失敗，請稍後重試\n" +
                "查看全部\n" +
                "確定\n" +
                "應用程式不支持在已獲取root權限的設備上運行。\n" +
                "應用版本無效。請刪除此應用並從應用商店重新下載\n" +
                "探索\n" +
                "訂餐\n" +
                "預訂\n" +
                "我的帳戶\n" +
                "設定\n" +
                "優惠券\n" +
                "再按一次退出應用\n" +
                "歡迎使用香格里拉手機應用程式！通過香格里拉手機應用程式，您將能夠直接享受香格里拉國際飯店管理有限公司及其關聯公司所管理之飯店、度假飯店和物業的預訂服務、獲得促銷和營銷資訊以及常客獎勵計劃等相關訊息。\\n\\n使用該應用程式需遵守《條款及細則》、《隱私保障政策》以及《Cookies政策》。如使用該應用程式，請點擊“我同意”確定您已理解並同意下列條款：\\n\\n• 《條款及細則》； \\n\\n• 依照《隱私保障政策》以及《Cookies政策》的相關約定收集、儲存和使用您的個人資訊；\\n\\n• 依照《隱私保障政策》使用您的個人數據，用於市場營銷和推廣目的。\\n\n" +
                "我同意\n" +
                "拒絕並關閉應用程式\n" +
                "《條款及細則》\n" +
                "《隱私保障政策》\n" +
                "《Cookies政策》\n" +
                "酒店WiFi\n" +
                "下一個目的地\n" +
                "三倍精彩獎勵\n" +
                "通過 App 預訂住宿，賺取高達 3X 積分。\n" +
                "條款與細則適用\n" +
                "三倍精彩獎勵\n" +
                "返回\n" +
                "抱歉，服務器異常，您可以致電香格里拉預訂或稍後再試。\n" +
                "網絡連接異常，請檢查您的網絡或稍後再試。\n" +
                "網絡連接已被禁用\n" +
                "設定\n" +
                "取消\n" +
                "網絡異常，請稍後再試。\n" +
                "您的登入狀態已失效，請登入后重試\n" +
                "查找酒店\n" +
                "企業商旅/特價（選填）\n" +
                "客房\n" +
                "客房\n" +
                "成人\n" +
                "成人\n" +
                "兒童\n" +
                "兒童\n" +
                "請選擇酒店\n" +
                "熱門目的地\n" +
                "熱門\n" +
                "近期搜尋\n" +
                "歷史搜尋\n" +
                "定位\n" +
                "抱歉，未找到相應內容\n" +
                "正在獲取您的位置\n" +
                "無法獲取您的位置\n" +
                "取消\n" +
                "EEE\n" +
                "確定選擇\n" +
                "日\n" +
                "一\n" +
                "二\n" +
                "三\n" +
                "四\n" +
                "五\n" +
                "六\n" +
                "入住日期\n" +
                "退房日期\n" +
                "退房日期\n" +
                "選擇日期\n" +
                "晚\n" +
                "晚\n" +
                "已添加到系統日曆中\n" +
                "該事項已經添加至日曆\n" +
                "無法添加到日曆\n" +
                "設定\n" +
                "暫不\n" +
                "請在設定中允許香格里拉使用您的日曆\n" +
                "請在設定中允許Shangri-la使用您的定位\n" +
                "請開啟相冊保存權限\n" +
                "請登入您的系統帳戶。\n" +
                "添加失敗，請稍後重試\n" +
                "線上預訂的最長入住時間為180晚。\n" +
                "報價資訊僅供參考。\n" +
                "房間\n" +
                "確定\n" +
                "成人\n" +
                "兒童（12歲以下）\n" +
                "兒童必須在12歲以下。\n" +
                "客房獎勵適用於雙人入住。三位或以上賓客入住同一間客房需額外付費。\n" +
                " + 增加客房\n" +
                "每間客房最多可入住%d位客人\n" +
                "本飯店提供兒童特別餐飲計劃。\n" +
                "註：如入住人數超出2位成人和1位兒童，請註明實際兒童人數及其年齡。酒店將盡量配合您家人的入住需求，如無法滿足您的需求，我們將通知您。\n" +
                "香禮券客房套餐常規限住2位客人，超出人數可能會產生額外費用， 詳見香禮券產品頁。 額外費用需要您在入住酒店期間付款。\n" +
                "兒童年齡需為12歲以下。\n" +
                "企業商旅/特價\n" +
                "優惠類型\n" +
                "房價代碼\n" +
                "輸入房價代碼\n" +
                "選擇代碼類型\n" +
                "公司客戶\n" +
                "團體\n" +
                "推廣代碼\n" +
                "旅行社\n" +
                "企業商旅特惠計劃\n" +
                "%1$s 積分 每晚\n" +
                "已售罄\n" +
                "如需查詢，請聯繫酒店\n" +
                "美食\n" +
                "休閒與健康\n" +
                "Spa\n" +
                "香禮券商城\n" +
                "更多\n" +
                "日期\n" +
                "特色\n" +
                "所需獎勵積分\n" +
                "兌換\n" +
                "預訂\n" +
                "電話\n" +
                "撥打\n" +
                "電子郵件\n" +
                "每晚\n" +
                "關於酒店\n" +
                "%1$s積分 每晚\n" +
                "每晚%1$s獎勵積分\n" +
                "還剩 %1$s 間房\n" +
                "還剩 %1$s 間房\n" +
                "抱歉，您所查找的日期暫時沒有房間可供預訂。請更改日期重新搜索。\n" +
                "複製\n" +
                "繼續\n" +
                "取消\n" +
                "好\n" +
                "郵箱已複製。\n" +
                "現金加積分\n" +
                "會員專屬價格\n" +
                "圖片\n" +
                "全部\n" +
                "酒店周邊地圖資訊\n" +
                "交通\n" +
                "景點\n" +
                "購物\n" +
                "娛樂\n" +
                "更多周邊資訊請諮詢酒店服務中心\n" +
                "導航\n" +
                "沒有可用地圖應用程式\n" +
                "高德地圖\n" +
                "百度地圖\n" +
                "Google 地圖\n" +
                "下拉重新載入...\n" +
                "載入更多...\n" +
                "正在載入...\n" +
                "載入更多\n" +
                "重試\n" +
                "下拉重新載入...\n" +
                "載入更多...\n" +
                "正在載入...\n" +
                "正在載入...\n" +
                "重新載入失敗\n" +
                "最後更新 今日 HH:mm\n" +
                "正在載入...\n" +
                "上拉載入更多\n" +
                "鬆開載入更多\n" +
                "正在載入...\n" +
                "正在載入...\n" +
                "載入失敗\n" +
                "正在載入…\n" +
                "已顯示全部內容\n" +
                "所需的權限\n" +
                "您的預訂將從列表中刪除\n" +
                "原預訂\n" +
                "確定\n" +
                "暫不取消\n" +
                "繼續取消\n" +
                "取消\n" +
                "確定\n" +
                "暂不取消\n" +
                "继续取消\n" +
                "根據您輸入的預訂確認號碼，未能查詢到預訂，請重新輸入\n" +
                "您输入的姓氏与预订中的姓氏不符, 请重新输入\n" +
                "您的訂單已取消, 取消號碼請您稍後重新載入當前頁面獲取, 請您保存取消號碼, 可能付款罰金\n" +
                "您是否確定申請退款？\n" +
                "訂房代號稍後將發送至您的郵箱。\n" +
                "房號:\n" +
                "晚\n" +
                "晚\n" +
                "再次預訂\n" +
                "再次兌換\n" +
                "取消\n" +
                "發票\n" +
                "刪除\n" +
                "辦理入住\n" +
                "線上退房\n" +
                "查找我的客房預訂記錄\n" +
                "預訂確認號碼\n" +
                "姓氏\n" +
                "登入查看我的預訂\n" +
                "登入查看我的禮券\n" +
                "登入\n" +
                "您目前沒有預訂記錄。\\n立即預訂\n" +
                "預訂住宿\n" +
                "暫未找到任何兌換禮券，請使用香格里拉會獎勵積分進行禮券兌換\n" +
                "禮券兌換\n" +
                "登入 查看我的香禮券\n" +
                "您目前沒有購買記錄\n" +
                "您目前沒有預訂記錄。\n" +
                "所有預訂\n" +
                "近期預訂\n" +
                "全部\n" +
                "查找\n" +
                "預訂取消號碼：\n" +
                "預訂確認號碼：\n" +
                "參考編號:\n" +
                "取消成功\n" +
                "您的訂單已取消, 取消號碼為%1$s。\n" +
                "確定\n" +
                "獎勵積分兌換\n" +
                "客房升級\n" +
                "延長住宿\n" +
                "獎勵積分加現金\n" +
                "積分\n" +
                "請用英文字母填寫\n" +
                "（如果有誤，請用英文字母填寫）\n" +
                "無法識別，請用英文字母填寫\n" +
                "有效日期至:\n" +
                "抱歉，取消失敗。請您稍後再試。\n" +
                "兌換碼:\n" +
                "申請退款\n" +
                "有效期至:\n" +
                "確定\n" +
                "取消\n" +
                "立即付款\n" +
                "取消付款\n" +
                "待付款\n" +
                "是否確認取消此訂單的付款\n" +
                "您已完成付款\n" +
                "抱歉，付款超時，請您重新下單\n" +
                "餐飲禮券\n" +
                "Spa禮券\n" +
                "參考編號:\n" +
                "扣除的積分:\n" +
                "兌換詳情\n" +
                "兌換信息\n" +
                "禮券數量:\n" +
                "有效日期至:\n" +
                "取消政策\n" +
                "個人信息\n" +
                "確定\n" +
                "立即預訂\n" +
                "立即加入\n" +
                "還未成為香格里拉會會員？\\n立即加入，盡享尊崇禮遇。\n" +
                "會籍號碼\n" +
                "密碼\n" +
                "密碼不正確，您還可以輸入%1$s次\n" +
                "密碼不正確，您還可以輸入%1$s次\n" +
                "忘記密碼\n" +
                "登入\n" +
                "啟動我的會員帳戶\n" +
                "會籍號碼/郵箱或密碼不正確，請重試。\n" +
                "請輸入密碼\n" +
                "您嘗試登入的次數已用完, 請20分鐘后再試。\n" +
                "請輸入會籍號碼\n" +
                "提高賬戶安全性\n" +
                "我們已實施雙重認證（2FA）以提高您的香格里拉會帳戶安全性。使用2FA時，系統將會要求您輸入一次性密碼（OTP）以進行關鍵交易或更改帳戶資訊。您可以選擇註冊您的電郵、手機號碼或兩者皆可。\n" +
                "使用手機號碼登錄\n" +
                "使用會籍號碼/已驗證的郵箱登入\n" +
                "已驗證的手機號碼\n" +
                "請輸入正確的國際區號\n" +
                "會籍號碼 / 郵箱\n" +
                "手機號碼\n" +
                "立即加入\n" +
                "更改為使用驗證碼\n" +
                "更改為使用密碼\n" +
                "1.點擊“重新發送”獲取新的驗證碼\\n2.選擇使用其他登入方式登入\n" +
                "1.請查看垃圾郵件文件夾\\n2.點擊“重新發送”獲取新的驗證碼\\n3. 選擇使用其他登入方式登入\n" +
                "忘記密碼?\n" +
                "Google驗證失敗。請稍後再試。\n" +
                "驗證碼\n" +
                "已驗證的電郵地址\n" +
                "請輸入正確的電子郵箱。\n" +
                "本機號碼\n" +
                "同意\n" +
                "手機一鍵登入/註冊\n" +
                "通過其他手機號註冊\n" +
                "為保證您的個人資訊安全，使用登入/註冊功能需要您先閱讀並同意相關條款。\n" +
                "操作失敗，請稍後重試\n" +
                "我的\n" +
                "帳戶記錄\n" +
                "兌換成員名單\n" +
                "我的資料\n" +
                "我的權益\n" +
                "帳戶設定\n" +
                "退出登入\n" +
                "立即兌換\n" +
                "積分餘額\n" +
                "黃金級\n" +
                "翡翠級\n" +
                "鑽石級\n" +
                "黃金\n" +
                "翡翠\n" +
                "鑽石\n" +
                "帝星\n" +
                "晚\n" +
                "等級積分\n" +
                "登入/註冊\n" +
                "入住並賺取住宿\n" +
                "還需%1$s晚入住升級至翡翠\n" +
                "還需%1$s晚入住升級至鑽石\n" +
                "%1$s 晚\\n本年度\n" +
                "入住或用餐賺取更多等級積分\n" +
                "還需%1$s等級積分升翡翠級\n" +
                "還需%1$s等級積分升鑽石級\n" +
                "%1$s 等級積分\\n本年度\n" +
                "感謝與您相識\n" +
                "天\n" +
                "天\n" +
                "感謝您的信任與支持\n" +
                "帳戶設定\n" +
                "修改密碼\n" +
                "設定密碼\n" +
                "暫不設定\n" +
                "通訊偏好\n" +
                "保存\n" +
                "選擇語言\n" +
                "您是否確定保存該資訊?\n" +
                "修改成功\n" +
                "您已升級至%1$s級會籍。\n" +
                "了解更多%1$s級別禮遇 &gt;\n" +
                "恭喜!\n" +
                "退出成功\n" +
                "翡翠級會籍續期所需的合資格間夜數\n" +
                "翡翠級會籍續期所需的合資格住宿次數\n" +
                "鑽石級會籍續期所需的合資格間夜數\n" +
                "鑽石級會籍續期所需的合資格住宿次數\n" +
                "順延間夜數：\n" +
                "積分\n" +
                "等級\n" +
                "會籍始於\n" +
                "有效期至\n" +
                "查看所有權益\n" +
                "重新載入\n" +
                "每60秒自動重新載入（XX秒）\n" +
                "登入郵箱\n" +
                "請輸入密碼以驗證您的身份\n" +
                "帳號密碼\n" +
                "下一步\n" +
                "* 此郵箱將用於登入您的香格里拉會帳戶。如需修改您的聯繫方式，請前往＂我的資料＂。\n" +
                "修改登入郵箱\n" +
                "驗證登入郵箱\n" +
                "提交\n" +
                "請輸入正確的帳號密碼\n" +
                "密碼輸入次數已用盡，您需要重新登入您的帳戶。\n" +
                "請輸入新的登入郵箱\n" +
                "郵箱\n" +
                "請輸入正確的郵箱\n" +
                "該郵箱已存在，請使用另一個郵箱。\n" +
                "確定將登入郵箱改為%1$s？\n" +
                "請點擊“發送”獲取驗證碼。\n" +
                "請輸入您的新登入郵箱，並點擊“發送”獲取驗證碼。\n" +
                "1. 請查看垃圾郵件文件夾。 \\n2. 點擊“重新發送”獲取新的驗證碼。\n" +
                "綁定成功\n" +
                "解綁成功\n" +
                "登入手機號碼\n" +
                "微信\n" +
                "解綁微信賬號\n" +
                "解綁微信後將無法使用微信登入，但您還可通過會籍號碼/已驗證的郵箱或手機號碼和密碼登入帳戶。您確定要解綁嗎？\n" +
                "綁定\n" +
                "立即解綁\n" +
                "解綁\n" +
                "請輸入您的登入手機號及驗證碼\n" +
                "添加登錄手機號碼\n" +
                "驗證登錄手機號碼\n" +
                "修改登錄手機號碼\n" +
                "*該手機號將作為您的登入和驗證方式。\n" +
                "1. 點擊“重新發送”獲取新的驗證碼。\n" +
                "請輸入一個不同的手機號碼.\n" +
                "由於您未設定密碼，解綁微信後將導致當前香格里拉會會員帳號無法使用。請先於\"帳戶設定\"中設定密碼，再解綁微信。若您需要幫助，敬請與我們聯繫：電郵至 golden.circle@shangri-la.com或致電+852 3069 9688。\n" +
                "Google \n" +
                "解綁Google 帳號\n" +
                "解綁Google 后將無法使用Google 登入，但您還可通過其他方式登入帳戶。 您確定要解綁嗎？\n" +
                "立即解綁\n" +
                "請點擊“發送”獲取驗證碼。\n" +
                "請輸入您的新手機號碼，並點擊“發送”獲取驗證碼。\n" +
                "請選擇國際區號\n" +
                "立即添加\n" +
                "通過登入郵箱驗證\n" +
                "通過登入手機號碼驗證\n" +
                "請點擊“發送”獲取驗證碼，驗證碼將發送至%1$s。\n" +
                "跳過（剩餘%d次） &gt;\n" +
                "跳過（剩餘%d次） &gt;\n" +
                "請驗證您的登錄郵箱或手機號碼\n" +
                "手機號碼 \\n%s %s\n" +
                "更新您的手機號碼\n" +
                "登入郵箱\n" +
                "選擇“登入郵箱”或“手機號碼”后，您也可以更新以上資訊。\n" +
                "確定\n" +
                "即將入住\n" +
                "預訂詳情\n" +
                "線上辦理入住\n" +
                "酒店詳情\n" +
                "地圖\n" +
                "告訴司機\n" +
                "致電\n" +
                "郵件\n" +
                "意見反饋\n" +
                "當地天氣\n" +
                "當地時間\n" +
                "添加到日曆\n" +
                "祝您旅途愉快!\n" +
                "豐富您的住宿體驗\n" +
                "獎勵積分\n" +
                "房號\n" +
                "預訂\n" +
                "智慧客房\n" +
                "已入住\n" +
                "已選服務\n" +
                "查看帳單\n" +
                "兌換積分\n" +
                "立即兌換\n" +
                "積分餘額\n" +
                "登入/註冊\n" +
                "客房獎勵\n" +
                "客房升等獎勵\n" +
                "非客房獎勵\n" +
                "生活品味獎勵\n" +
                "將積分轉換為里程\n" +
                "兌換全球任意一家香格里拉酒店、度假酒店、嘉里酒店、盛貿酒店或JEN酒店的客房獎勵。\n" +
                "您可憑香格里拉會獎勵積分，將已確認預訂的標準客房升等至豪華閣/盛貿閣客房或行政套房，盡享至臻奢華及更個性化的服務。\n" +
                "您可憑積分兌換全球香格里拉旗下酒店的餐飲或Spa消費禮券，品嘗美味佳饌或體驗香格里拉Chi Spa。\n" +
                "憑香格里拉會獎勵積分，您可兌換一系列誘人獎勵，從電子用品、電子禮卡，到香格里拉專屬產品，應有盡有，精彩紛呈。\n" +
                "您可將積分轉換為我們的航空公司合作夥伴之飛行里數。\n" +
                "交易記錄\n" +
                "在指定期間沒有找到任何交易記錄\n" +
                "最近3個月\n" +
                "最近24個月\n" +
                "獎勵積分兌換\n" +
                "非客房獎勵\n" +
                "餐飲禮券\n" +
                "SPA禮券\n" +
                "獎勵積分\n" +
                "如何兌換你的非客房獎勵\n" +
                "禮券種類\n" +
                "禮券數量:\n" +
                "所需積分\n" +
                "下一步\n" +
                "很抱歉，目前您的香格里拉會獎勵積分無法達到您的兌換需求，請修改禮券數量。\n" +
                "此優惠券不適用於這家酒店。\n" +
                "酒店/地區名稱\n" +
                "請輸入酒店或地區名稱\n" +
                "積分\n" +
                "客房獎勵\n" +
                "獎勵積分兌換\n" +
                "延長住宿\n" +
                "您可憑您的香格里拉會獎勵積分，兌換全球任一家香格里拉集團旗下飯店的住宿，讓您與家人盡享非凡住宿體驗。\n" +
                "如果想在香格里拉多住幾天，您可在付費住宿之餘憑獎勵積分兌換額外一晚或數晚的住宿。此項獎勵僅限會員本人使用。\n" +
                "客房獎勵兌換表\n" +
                "您目前沒有預訂記錄。\n" +
                "客房升級獎勵兌換表\n" +
                "積分轉換里程\n" +
                "飛行常客飛行計劃列表\n" +
                "飛行常客飛行計劃會籍\n" +
                "積分\n" +
                "轉換為\n" +
                "取消政策\n" +
                "特別優惠\n" +
                "我已經閱讀並同意香格里拉會\n" +
                "我已經閱讀並同意香格里拉會積分轉換里程-相關條款細則。\n" +
                "繼續\n" +
                "取消\n" +
                "很抱歉，目前您的香格里拉會獎勵積分無法達到您的轉換需求。\n" +
                "請輸入您的\\n帳戶密碼以確認轉換。\n" +
                "請同意相關條款與細則\n" +
                "請選擇飛行常客會籍號碼\n" +
                "立即轉換\n" +
                "選擇飛行常客飛行計劃會籍\n" +
                "編輯\n" +
                "新增\n" +
                "暫無飛行常客飛行計劃會籍\n" +
                "積分轉換里程已提交成功\n" +
                "轉換詳情\n" +
                "其他郵箱地址\n" +
                "發送\n" +
                "完成\n" +
                "將確認電郵發送至另一郵箱:\n" +
                "請輸入有效的電子郵箱\n" +
                "訊息中心\n" +
                "全部已讀\n" +
                "沒有更多訊息。\n" +
                "訊息詳情\n" +
                "選擇\n" +
                "立即前往\n" +
                "語言\n" +
                "貨幣\n" +
                "清除暫存\n" +
                "允許通知\n" +
                "手機辦理入住/退房、獎勵兌換等\n" +
                "關閉通知後，您將無法及時收到有關預訂或香格里拉會的提醒。您確定要繼續嗎?\n" +
                "聯絡我們\n" +
                "反饋建議\n" +
                "條款與細則\n" +
                "隱私保障政策\n" +
                "清除成功\n" +
                "對不起, 您需要先開啟\"通知\"權限\n" +
                "關於\n" +
                "版本\n" +
                "評分\n" +
                "沒有找到可以評分的應用商店程式\n" +
                "個性化內容推薦\n" +
                "開啟后將展示個性化推薦內容\n" +
                "Cookies 政策\n" +
                "貨幣選擇\n" +
                "語言\n" +
                "簡體中文\n" +
                "簡體中文\n" +
                "English\n" +
                "日本語\n" +
                "投影\n" +
                "系統定位服務已關閉\n" +
                "投影是基於局域網的服務，需開啟位置服務，獲取當前網絡資訊。\n" +
                "設定\n" +
                "取消\n" +
                "請輸入預訂確認號碼\n" +
                "請輸入您的姓氏\n" +
                "我的信用卡\n" +
                "您還未添加信用卡\n" +
                "添加信用卡\n" +
                "已過期\n" +
                "(預設)\n" +
                "* 您最多可保存6張信用卡。\n" +
                "信用卡\n" +
                "查看支付政策\n" +
                "設定為預設\n" +
                "保存\n" +
                "已設定為預設\n" +
                "信用卡\n" +
                "條款與細則\n" +
                "信用卡保存方式\n" +
                "• CVV/CVN2將不會被保存。\\n• 中國銀聯卡的有效期將不會被保存。\n" +
                "保存我的信用卡信息, 以供將來使用。我已經閱讀, 理解並同意條款與細則和信用卡保存方式。\n" +
                "選擇信用卡類型\n" +
                "信用卡卡號\n" +
                "持卡人姓名\n" +
                "有效期(月/年)\n" +
                "確定\n" +
                "確認刪除此信用卡信息嗎 ?\n" +
                "信用卡有效期早於當前月份\n" +
                "請選擇信用卡類型\n" +
                "請輸入信用卡號\n" +
                "請輸入持卡人姓名\n" +
                "請選擇信用卡有效期\n" +
                "請選擇信用卡類型\n" +
                "您填寫的卡號無效\n" +
                "請選擇信用卡有效期\n" +
                "確認\n" +
                "取消\n" +
                "好\n" +
                "好\n" +
                "確定\n" +
                "請選擇此項以繼續\n" +
                "月份\n" +
                "年份\n" +
                "是\n" +
                "否\n" +
                "熱門國家\n" +
                "跳過\n" +
                "開始使用\n" +
                "發現新的版本\n" +
                "載入失敗，請稍後再試…\n" +
                "網絡連接失敗，請檢查您的網絡或稍後再試。\n" +
                "請啟用位置服務\n" +
                "沒有內容\n" +
                "正在載入...\n" +
                "重試\n" +
                "Primary Channel\n" +
                "Secondary Channel\n" +
                "debug調試通知\n" +
                "點擊打開調試頁面\n" +
                "關閉通知提示\n" +
                "輸入下圖中的字元。（不分大小寫）\n" +
                "輸入圖中的字元\n" +
                "輸入圖中的字元。（不分大小寫）\n" +
                "請稍後再試。\n" +
                "網絡異常，請稍後再試。\n" +
                "飛行常客飛行計劃會籍\n" +
                "編輯\n" +
                "新增常旅客飛行計劃\n" +
                "暫無飛行常客飛行計劃會籍\n" +
                "請選擇飛行常客飛行計劃會籍\n" +
                "新增飛行常客飛行計劃會籍\n" +
                "編輯飛行常客飛行計劃會籍\n" +
                "相同飛行常客飛行計劃會籍只能保存一個\n" +
                "飛行常客會籍號碼\n" +
                "您所提供的飛行常客會籍號碼不存在\n" +
                "請選擇飛行常客飛行計劃會籍\n" +
                "請輸入飛行常客會籍號碼\n" +
                "保存\n" +
                "編輯\n" +
                "(已保存)\n" +
                "微信\n" +
                "FaceBook\n" +
                "朋友圈\n" +
                "更多\n" +
                "複製連結\n" +
                "複製成功\n" +
                "操作失敗，請稍後重試\n" +
                "未找到應用程式\n" +
                "生成海報\n" +
                "商品海報\n" +
                "保存圖片\n" +
                "分享微信好友\n" +
                "分享朋友圈\n" +
                "保存成功\n" +
                "保存失敗，請稍後重試\n" +
                "%d家酒店適用\n" +
                "微信掃碼/長按圖片 查看商品詳情\n" +
                "微信掃碼 / 長按圖片進入程式\n" +
                "圖片載入失敗，請稍後重試\n" +
                "加入香格里拉會(1/3)\n" +
                "稱謂\n" +
                "姓氏\n" +
                "名字\n" +
                "出生日期\n" +
                "郵箱\n" +
                "國家/地區\n" +
                "手機號碼\n" +
                "國際區號\n" +
                " 所有欄位必填\n" +
                "* 香格里拉會只接受年滿18歲的人士申請成為會員。\n" +
                "請選擇稱謂\n" +
                "請使用英文字母填寫\n" +
                "請選擇您的出生日期\n" +
                "請輸入正確的郵箱\n" +
                "請選擇您的國家/地區\n" +
                "請輸入正確的手機號碼。\n" +
                "下一步\n" +
                "手機號碼\n" +
                "電郵地址\n" +
                "通過手機驗證\n" +
                "通過郵箱驗證\n" +
                "請點擊“發送”獲取驗證碼，驗證碼將發送至%1$s。\n" +
                "發送\n" +
                "請輸入驗證碼\n" +
                "收不到驗證碼?\n" +
                "重新發送\n" +
                "秒\n" +
                "請輸入有效驗證碼\n" +
                "登入\n" +
                "取消\n" +
                "1. 點擊“重新發送”獲取新的驗證碼。 \\n2. 選擇使用郵箱驗證。\n" +
                "1. 請查看垃圾郵件文件夾。 \\n2. 點擊“重新發送”獲取新的驗證碼。 \\n3. 選擇使用手機驗證。\n" +
                "我的藍牙房卡\n" +
                "領取房卡\n" +
                "房間號\n" +
                "條款與細則\n" +
                "我已閱讀並同意相關條款與細則。\n" +
                "正在為您解鎖無卡入住體驗…\n" +
                "整個過程需要大約15秒\n" +
                "告別實體房卡\n" +
                "手機一鍵開門\n" +
                "網絡環境不穩定，感謝您的耐心等候\n" +
                "藍牙房卡領取成功，立即體驗吧\n" +
                "確定\n" +
                "好的\n" +
                "聯繫我們\n" +
                "請同意相關條款與細則\n" +
                "藍牙房卡領取失敗。\n" +
                "再試一次\n" +
                "取消\n" +
                "開鎖失敗\n" +
                "抱歉，我們遇到了一些技術問題。\n" +
                "請核對您的房間號。\n" +
                "藍牙房卡僅可在距離門鎖1米範圍內使用。\n" +
                "請將手機接觸門鎖感應器\n" +
                "開鎖成功，請在5秒內打開房門\n" +
                "您當前沒有可使用的藍牙房卡\n" +
                "1. 從APP首頁找到您的藍牙房卡\n" +
                "2. 點擊鑰匙圖標激活藍牙房卡\n" +
                "3. 將手機接觸門鎖\n" +
                "下一步\n" +
                "預訂信息已更新，請重新領取藍牙房卡。\n" +
                "窗簾\n" +
                "空調\n" +
                "風速\n" +
                "模式\n" +
                "燈光\n" +
                "開/關\n" +
                "溫度\n" +
                "請勿頻繁操作\n" +
                "全部開啟\n" +
                "全部關閉\n" +
                "窗簾\n" +
                "紗簾\n" +
                "指令發送中\n" +
                "已關閉\n" +
                "已開啟\n" +
                "燈光已開啟\n" +
                "燈光已關閉\n" +
                "All Keys: The key is not valid in the current lock mode or cycle. Lock is typically in an invalid mode. This code may also appear if you use standard or display keys when the PPK or SPK LEDs are flashing.\n" +
                "Standard, Special, PPK and SPK Keys: The lock is in shutdown cycle because 10 or more invalid keys were used. A valid key must be used to terminate shutdown mode.\n" +
                "Standard Keys: Lock level is non-operating for this key’s type. The key does not belong to this lock.\n" +
                "Standard and Special Keys: Key is not mastered into the lock. The key does not belong to this lock.\n" +
                "Standard Keys: Key does not have one of the 12 valid pass numbers required for the pass level.\n" +
                "Standard and Special Keys: Key is an old key; its new key date is earlier than the lock’s key data. Replace the key with a current or new key.\n" +
                "Standard and Special Keys: Key is an old key; its new key time is earlier than the lock’s key data. Replace the key with a current or new key.\n" +
                "Standard and Special Keys: Key is an old key, level has limited sequence range (1-15) but key’s sequence number is older than the lock’s key data. Replace key with a current or new key. Use a re-sequence key if necessary.\n" +
                "Standard and Special Keys: Key is too new, level has limited sequence range and key’s sequence number is beyond the lock’s key data and range. Make and use a re-sequence key, then try the original key again.\n" +
                "Standard Key: Key is a limited use key and has already been used the maximum number of times. Replace key with a new key.\n" +
                "Standard Key: The key is a new key but the door is dead bolted and the new key cannot be accepted. If key is for a new guest, the room is still occupied. Assign new guest to another room.\n" +
                "All Keys: The key is expired based on the lock’s clock date and time. Replace key with a duplicate key with a later expiration date and time.\n" +
                "Standard Key: Key is current but key’s level is inhibited. Replace key with a new key.\n" +
                "Special Key: Key is current but key is inhibited. Replace key with a new key.\n" +
                "Standard Key: Key’s level is electronically locked out. If this key is a dual, electronic lock/unlock, inhibit level, or unlatch/latch key; it will not perform its function. The electronic unlock key must be used to remove the electronic lockout.\n" +
                "Standard Key: Key is an opening key, but the lock is dead bolted and the key cannot override it.\n" +
                "Standard Key: The key is new and is identified as a pre-reg key which will not work until its check-in date and time. If desired, replace key with a new key.\n" +
                "Generic Error\n" +
                "BLE Status: %s\n" +
                "已登記入住\n" +
                "鑒於安全考慮，我們需要獲取您的位置資訊。點擊“允許”開啟定位服務。\n" +
                "鑒於安全考慮，我們需要獲取您的位置資訊。點擊“重試”開啟定位服務。\n" +
                "允許\n" +
                "拒絕\n" +
                "獲取定位失敗\n" +
                "押金預授權成功\n" +
                "查看押金明細\n" +
                "預計抵達時間\n" +
                "備選要求\n" +
                "*您的要求無法保證一定能夠滿足，將根據酒店實際情況而定。\n" +
                "繼續\n" +
                "確定\n" +
                "取消\n" +
                "我同意\n" +
                "返回\n" +
                "再試一次\n" +
                "重試\n" +
                "根據公安機關要求，我們需要核驗您的身份信息以完成入住流程。\\n我們與騰訊合作，通過其”騰訊E證通“小程序完成身份信息及面部識別照片的採集及核驗，我們將接受“騰訊E證通”傳回的身份核驗信息，委託騰訊協助向公安機關指定系統上傳您的身份信息。\\n如希望繼續辦理，請點擊“我同意”確認您已知悉並同意上述安排。請注意，您即將跳轉至騰訊E證通頁面並開通其服務，騰訊將收集和處理您的個人信息，請仔細閱讀其授權協議並考慮是否同意。如您同意的，請根據提示完成您的身份信息採集及面部識別核驗。\n" +
                "身份驗證成功\n" +
                "身份驗證失敗\n" +
                "其他雜費\n" +
                "房費\n" +
                "預授權總額\n" +
                "付款方式\n" +
                "抱歉，我們遇到了一些技術問題。\n" +
                "未找到應用程式\n" +
                "客服小香為您服務\n" +
                "點擊進入\n" +
                "配置載入失敗\n" +
                "啟動網上帳戶\n" +
                "請提供以下資訊來啟用您的帳戶。\n" +
                "會籍號碼\n" +
                "點擊“重新發送”獲取新的驗證碼\n" +
                "通過郵箱啟動賬戶\n" +
                "請輸入正確的會籍號碼\n" +
                "請輸入正確的手機號碼\n" +
                "登入\n" +
                "提交\n" +
                "我的優惠券\n" +
                "待使用\n" +
                "已失效\n" +
                "兌換碼:\n" +
                "有效期:\n" +
                "暫無可用優惠券\n" +
                "優惠券詳情\n" +
                "申請退款\n" +
                "兌換碼\n" +
                "有效期\n" +
                "適用酒店\n" +
                "關聯客房訂單號\n" +
                "查看適用酒店\n" +
                "立即使用\n" +
                "未到使用時間\n" +
                "線上預約\n" +
                "查找酒店\n" +
                "選擇入住日期\n" +
                "選擇入住人數\n" +
                "加入香格里拉會\n" +
                "尊享一系列會員專屬權益、會員專屬價格及精彩禮遇\n" +
                "其他登錄方式\n" +
                "返回其他登錄選項\n" +
                "微信\n" +
                "手機號碼\n" +
                "立即登入\n" +
                "前往註冊\n" +
                "已經是會員？請點擊此處登入\n" +
                "此處\n" +
                "* 您的密碼需包含至少8個字元，其中必須包括(a – z, A – Z) 英文字母及(0 – 9)數字，即其中至少包含一個數字。\n" +
                "我希望收到帳戶更新資訊、香格里拉會最新消息，以及香格里拉及精選合作夥伴為會員提供的專享禮遇。\n" +
                "姓\n" +
                "名\n" +
                "帳戶密碼\n" +
                "1.點擊“重新發送”獲取新的驗證碼\\n2.選擇使用電郵驗證\n" +
                "1.請查看垃圾郵件文件夾\\n2.點擊“重新發送”獲取新的驗證碼\\n3.選擇使用手機驗證\n" +
                "通訊偏好\n" +
                "本人已閱讀並同意香格里拉會條款與細則、隱私政策及Cookies政策。\n" +
                "條款與細則\n" +
                "隱私政策\n" +
                "Cookies政策\n" +
                "註冊成功！\n" +
                "歡迎加入香格里拉會\n" +
                "盡享我們為您用心策劃的升級會員禮遇!\\n您的會籍號碼為：\n" +
                "完善您的個人信息，讓我們爲您提供更周到的服務。\n" +
                "性別\n" +
                "請選擇\n" +
                "請保存您的會籍號碼以備後用。\n" +
                "授權失敗，請重試。\n" +
                "您的會籍已經升級！\n" +
                "恭喜成為帝星會員！\n" +
                "恭喜升級。\\n立即探索翡翠會籍權益 &gt;\n" +
                "恭喜升級。\\n立即探索鑽石會籍權益 &gt;\n" +
                "探索豐富體驗和精彩禮遇 &gt;\n" +
                "全部\n" +
                "待支付\n" +
                "待入住\n" +
                "已完成\n" +
                "立即登錄以查看預訂、在線辦理入住並探索更多會員獎勵。\n" +
                "您目前沒有任何預訂記錄。\n" +
                "您目前沒有預訂記錄。\\n看看下面的推薦，準備下一個行程，我們隨時為您提供幫助。\n" +
                "添加行程\n" +
                "查找我的預訂記錄\n" +
                "近期訂單\n" +
                "預訂詳情\n" +
                "服務與設施\n" +
                "行程偏好\n" +
                "客房服務\n" +
                "洗衣\n" +
                "打掃客房\n" +
                "行李協助\n" +
                "猜你喜歡\n" +
                "查看更多\n" +
                "登入\n" +
                "登入以查看可用的優惠券。\n" +
                "暫無可用優惠券\n" +
                "商城\n" +
                "優惠\n" +
                "酒店\n" +
                "From\n" +
                "下一站目的地\n" +
                "住宿\n" +
                "餐飲\n" +
                "購物\n" +
                "探索\n" +
                "平均每晚由%1$s %2$s起\n" +
                "每%1$s晚由%2$s %3$s起\n" +
                "暫不需要\n" +
                "不再提醒\n" +
                "適用於多家酒店\n" +
                "永久註銷帳戶\n" +
                "重要提醒\n" +
                "在您註銷帳戶後：\n" +
                "確認註銷\n" +
                "稍後決定\n" +
                "已提交請求\n" +
                "確認\n" +
                "您是否確認提交註銷申請？申請註銷帳戶后您將自願放棄帳戶內所有資產。\n" +
                "領券中心\n" +
                "贈送好友\n" +
                "確定贈送優惠券給好友?\n" +
                "成功贈送給好友後不可申請退款。若24小時好友未領取，券將自動退回。\n" +
                "立即贈送\n" +
                "取消\n" +
                "支持轉贈\n" +
                "確認取消轉贈？\n" +
                "對方將無法正常領取。\n" +
                "取消轉贈\n" +
                "關閉視窗\n" +
                "選擇祝福\n" +
                "同意\n" +
                "《贈送條款與細則》\n" +
                "請同意相關條款細則。\n" +
                "立即贈送\n" +
                "贈送規則\n" +
                "好友贈送您一個禮物，點擊領取！\n" +
                "點擊立即贈送後，優惠券即變更為轉贈中狀態。 在對方接受前可在券詳情頁面取消轉贈。\n" +
                "重新開立發票只能申請一次，申請後，原發票將作廢，無法進行報銷。\n" +
                "申請發票\n" +
                "查看發票詳情\n" +
                "發票狀態已改變。\n" +
                "確認\n" +
                "取消\n" +
                "確定\n" +
                "填寫發票信息\n" +
                "開票金額\n" +
                "發票類型\n" +
                "增值稅普通發票\n" +
                "增值稅電子普通發票\n" +
                "抬頭類型\n" +
                "企業\n" +
                "個人\n" +
                "發票抬頭\n" +
                "統編\n" +
                "納稅人識別號\n" +
                "發票內容\n" +
                "預付卡銷售\n" +
                "接收郵箱\n" +
                "提交申請\n" +
                "請選擇發票抬頭\n" +
                "請填寫需要開具發票的姓名\n" +
                "您輸入的電子郵箱地址有誤\n" +
                "酒店將優先使用電子郵件的方式向客人提供電子發票。若酒店不具備開立電子發票的功能， 則通過快遞的方式向客人寄送紙本發票。\n" +
                "注意事項：\\n1. 請仔細核對您填寫的發票資訊，以免再次修改。\\n2. 按照新發票資訊重開發票後，舊抬頭對應的發票將被作廢，無法進行報銷，新抬頭的發票將會以電郵形式發送至您上次開立發票的郵箱中。\n" +
                "申請重開發票\n" +
                "申請發票後將不支援線上退款，如需退款可致電酒店諮詢。是否確認申請發票？\n" +
                "發票接收人信息\n" +
                "收件人\n" +
                "請輸入收件人姓名\n" +
                "手機號\n" +
                "請輸入收件人手機號\n" +
                "請輸入聯繫郵箱\n" +
                "詳細地址\n" +
                "請填寫省、市、區、街道及大廈的詳細地址\n" +
                "請輸入正確的手機號\n" +
                "請輸入正確的郵箱\n" +
                "請輸入詳細地址\n" +
                "請輸入正確的姓名\n" +
                "請輸入正確的地址\n" +
                "發票申請已提交\n" +
                "增值稅電子普通發票預計在24小時內發送至郵箱，您也可以直接在客戶端查看下載。\n" +
                "返回我的優惠券\n" +
                "發票詳情\n" +
                "抬頭名稱\n" +
                "寄送方式\n" +
                "郵寄\n" +
                "電子郵件\n" +
                "快遞公司\n" +
                "快遞單號\n" +
                "郵寄地址\n" +
                "發票狀態\n" +
                "重開發票\n" +
                "重新發送發票\n" +
                "查看發票\n" +
                "已重開一次，不支持再次重開\n" +
                "提交\n" +
                "提交成功，發票將發送至您的郵箱，請及時查收。\n" +
                "我知道了\n" +
                "線上\\n客服\n" +
                "關係\n" +
                "請選擇關係\n" +
                "類型\n" +
                "成員\n" +
                "兒童成員\n" +
                "狀態\n" +
                "手機\n" +
                "電子郵箱\n" +
                "您確定要從家庭會籍中刪除所選的成員/兒童成員嗎？數據將全部刪除。\n" +
                "添加兌換成員\n" +
                "管理兌換成員\n" +
                "家庭成員（18歲及以上），並為香格里拉會的會員方有資格享受所屬等級的會籍權益。兒童成員只可享受兒童權益。\n" +
                "每個日曆年最多可提名 %1$s 位個人成為家庭會籍。您可在%2$s天後為成員進行兌換。\n" +
                "活躍\n" +
                "未完成\n" +
                "已邀請\n" +
                "等待確認\n" +
                "請在兌換前填寫被成員的資料。您想繼續嗎？\n" +
                "添加成員\n" +
                "成人\n" +
                "兒童（年齡&lt;18）\n" +
                "本日曆年內可添加成員/兒童成員的剩餘額度：%1$s\n" +
                "成員是否為香格里拉會會員？\n" +
                "會籍號碼\n" +
                "請輸入有效的香格里拉會會籍號碼。\n" +
                "姓\n" +
                "出生日期無效\n" +
                "我們將向成員發出邀請，解鎖獨家權益！\n" +
                "我已被授權將成員加入我的家庭會籍，並訪問成員的資訊。\n" +
                "我同意將兒童成員加入我的家庭會籍。\n" +
                "確認並邀請\n" +
                "確認\n" +
                "如果您希望繼續，請選擇此項。\n" +
                "請輸入有效的手機號碼或電郵。\n" +
                "添加成功！\n" +
                "我們將通過會員向兒童成員發出邀請。\n" +
                "編輯成員\n" +
                "請聯繫會員服務中心修改不可編輯的部分。\n" +
                "聯繫信息\n" +
                "請提供手機號碼或電郵\n" +
                "家庭會籍\n" +
                "兌換成員列表\n" +
                "成員（18歲及以上）有資格享受各種會籍權益和專享優惠。兒童成員只可享受兒童權益。\n" +
                "每個日曆年最多可提名 X 位個人成為家庭會籍。\n" +
                "用戶\n" +
                "兌換成員\n" +
                "發送邀請\n" +
                "請選擇您的首選邀請渠道\n" +
                "手機號碼\n" +
                "電郵\n" +
                "邀請\n" +
                "編輯\n" +
                "刪除\n" +
                "發送成功！\n" +
                "邀請失敗\n" +
                "成員將收到註冊加入香格里拉會的邀請。\n" +
                "很遺憾，您的邀請未能發送。請稍後再試。\n" +
                "請在成員的資料中補充手機號/電郵即可發送邀請\n" +
                "暫無兌換成員資訊\n" +
                "暫無兌換成員資訊\n" +
                "感謝您的預訂，請評價我們的應用程式！\n" +
                "退房結賬成功？請評價我們的應用程式。\n" +
                "感謝您的購買，請評價我們的應用程式！\n" +
                "您的意見對我們來說很重要\n" +
                "請給我們好評\n" +
                "提供反饋和建議\n" +
                "關閉\n" +
                "查找酒店\n" +
                "我的預訂\n" +
                "我的優惠券\n" +
                "我的帳戶\n" +
                "保存圖片\n" +
                "保存成功\n" +
                "保存失敗\n" +
                "位置權限使用說明\n" +
                "我們需要獲取您的位置，以便為您找到附近的酒店，提升您的瀏覽體驗，不開放該權限不影響應用程式正常使用。\n" +
                "綁定您的預訂記錄\n" +
                "酒店信息\n" +
                "預訂確認號碼\n" +
                "酒店名稱\n" +
                "入住和退房日期\n" +
                "請選擇酒店名稱\n" +
                "請選擇您的入住和退房日期\n" +
                "請輸入您的預訂確認號碼\n" +
                "搜尋預訂記錄\n" +
                "全選\n" +
                "我們已經收到您的請求。您可稍後在您的帳戶查看有關預訂紀錄。\n" +
                "我知悉並同意將所選預訂記錄綁定至(本人之)香格里拉會會籍。\n" +
                "請確認您知悉並同意綁定預訂紀錄聲明。\n" +
                "查找酒店\n" +
                "商務信息\n" +
                "添加\n" +
                "商務郵箱\n" +
                "有效期限\n" +
                "延長綁定\n" +
                "恢復\n" +
                "目前您尚未添加任何商務信息。\n" +
                "刪除商務郵箱\n" +
                "確認刪除此商務郵箱？刪除后將無法快速預訂貴司的企業報價\n" +
                "確認\n" +
                "取消\n" +
                "添加商務郵箱\n" +
                "恢復商務郵箱\n" +
                "請輸入您的商務郵箱，然後點擊“發送”，接收驗證碼。\n" +
                "請點擊“發送”，獲取驗證碼。驗證碼將發送至 %1$s\n" +
                "請輸入有效的電子郵件地址\n" +
                "輸入驗證碼\n" +
                "請輸入有效的驗證碼。\n" +
                "未收到驗證碼？\n" +
                "1.請仔細查看您的垃圾郵件箱\\n2.點擊“重發”，重新發送驗證碼。\n" +
                "提交";
        String[] keys = languageKey.split("\n");
        String[] values = languageValue.split("\n");
        //<string name="cbs_add_submit">提交</string>
        for (int i = 0; i < keys.length; i++) {
            System.out.println("<string name=\"" + keys[i] + "\">" + values[i] + "</string>");
        }
    }

    public static void main(String[] args) {
//        String cnLanguage = "<string name=\"cbs_add_submit\">提交</string>";
//
//        int start = cnLanguage.indexOf('>');
//        int end = cnLanguage.indexOf('<', start + 1);
//        System.out.println(cnLanguage.substring(0, start+1) + "嗨" + cnLanguage.substring(end));

//        Base aaa = null;
//        System.out.println((AAA)aaa);

//        String aaa = "from CNY 5,000 / per night";
//        System.out.println(aaa.indexOf("from"));
//        System.out.println(aaa.indexOf("CNY"));
//        System.out.println(aaa.indexOf("5,000"));
//        System.out.println(aaa.indexOf(""));


//        List<String> aaaa = new ArrayList<>(Arrays.asList(
//                "a",
//                "b",
//                "",
//                "c",
//                "d",
//                null,
//                "",
//                "e"
//        ));
//        for (int i = aaaa.size() - 1; i >= 0; i--) {
//            String str = aaaa.get(i);
//            if (str == null || str.length() == 0){
//                aaaa.remove(i);
//            }
//        }
//        System.out.println(aaaa);

//        Integer intValue = null;
//        int aaa = intValue;
//        System.out.println(aaa);

//        String replace = "每晚赚取积分{0}/晚现金支付部分".replace("{0}", "1,500");
//        System.out.println(replace);

        String localUrlStr = "        \"APP_PRIVACY_POLICY\": \"https://www.shangri-la.com/en/corporate/policies-pledges/app-privacy-policy/\",\n" +
                "        \"APP_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/apptermsconditions.html\",\n" +
                "        \"COOKIES_POLICY\": \"https://www.shangri-la.com/en/corporate/policies-pledges/app-cookies-policy/\",\n" +
                "        \"NON_ROOM_AWARDS_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/nonroomawardstermsconditions.html\",\n" +
                "        \"REDEMPTION_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/redemptiontermsconditions.html\",\n" +
                "        \"ROOM_UPGRADE_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/roomupgradetermsconditions.html\",\n" +
                "        \"TERMS_CONDITIONS\": \"https://www.shangri-la.com/en/corporate/shangrilacircle/terms-conditions/\",\n" +
                "        \"APP_CONTACT_US\": \"slscheme://app/WebView?url=https://m.shangri-la.com/en/app/contact/phone.html\",\n" +
                "        \"APP_CONTACT_US_HW\": \"slscheme://app/WebView?url=https://m.shangri-la.com/en/app/contact/huaweiphone.html\",\n" +
                "        \"POINTS_TO_MILES\": \"http://m.shangri-la.com/en/app/points/miles.html\",\n" +
                "        \"POINTS_TO_MILES_TERMS_CONDITIONS\": \"http://m.shangri-la.com/en/app/policy/pointstomilestermsconditions.html\",\n" +
                "        \"APP_BENEFITS\": \"https://m.shangri-la.com/en/touch/gc/benefits/?type=0\",\n" +
                "        \"REDEEM_LIFESTYLE\": \"https://www.shangri-la.com/corporate/golden-circle/redeem-points/lifestyle/\",\n" +
                "        \"OFFER_DETAIL\": \"{h5Domain}en/{offerPath}\",\n" +
                "        \"VOUCHER_DETAIL\": \"{h5Domain}en/touch/coupon-detail?dealCode={dealCode}\",\n" +
                "        \"RESTAURANT_DETAIL\": \"{h5Domain}en/fb/restaurant-detail?restaurantId={restaurantId}\",\n" +
                "        \"OFFER_GLOBAL_HOMEPAGE\": \"{h5Domain}en/touch/offers\",\n" +
                "        \"OFFER_HOTEL_HOMEPAGE\": \"{h5Domain}en/touch/{cityAlias}/{hotelAlias}/offers\",\n" +
                "        \"VOUCHER_SHOP\": \"{h5Domain}en/touch/market\",\n" +
                "        \"VOUCHER_HOTEL_SHOP\": \"{h5Domain}en/touch/market-hotel?hotelCode={hotelCode}\",\n" +
                "        \"VOUCHER_APPLICABLE_SITE\": \"{h5Domain}en/touch/coupon-applicable-site/?orderId={orderId}&certId={certId}\",\n" +
                "        \"VOUCHER_CENTER\": \"{h5Domain}en/touch/voucher-center/\",\n" +
                "        \"UNROOM_REDEEM\": \"{h5Domain}en/touch/market-points-voucher/\",\n" +
                "        \"WELCOME_AMENITY\": \"{h5Domain}en/touch/welcome-amenities/?type={level}\",\n" +
                "        \"REDEEM_BOUTIQUE\": \"https://boutique.shangri-la.com/index.php?lang=en&WT.mc_id=SLEB_20230308_MULTI_ORGANICSOCIAL_SLC-APP_ALWAYSON_OTHERS-DISPLAY-COLLECTION_PTS-REDEEM-REFER_EN\",\n" +
                "        \"MEMBER_BENEFIT_CAMPAIGN\": \"{h5Domain}en/corporate/member-benefit-campaign/list\"";

        Map<String, String> localMap = new HashMap<>();
        for (String s : localUrlStr.split("\n")) {
            String[] split = s.split(": ");
            localMap.put(split[0], split[1]);
        }

        String onlineUrlStr = "\"APP_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/apptermsconditions.html\",\n" +
                "        \"MEMBER_BENEFIT_CAMPAIGN\": \"https://www.shangri-la.com/en/corporate/member-benefit-campaign/list/\",\n" +
                "        \"POINTS_TO_MILES_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/pointstomilestermsconditions.html\",\n" +
                "        \"REDEEM_LIFESTYLE\": \"https://www.shangri-la.com/en/corporate/shangrilacircle/redeem-points/lifestyle/\",\n" +
                "        \"TERMS_CONDITIONS\": \"https://www.shangri-la.com/en/corporate/shangrilacircle/terms-conditions/?source=APP\",\n" +
                "        \"APP_PRIVACY_POLICY\": \"https://www.shangri-la.com/en/corporate/policies-pledges/app-privacy-policy/?source=APP\",\n" +
                "        \"VOUCHER_DETAIL\": \"{h5Domain}en/touch/coupon-detail?dealCode={dealCode}\",\n" +
                "        \"VOUCHER_CENTER\": \"{h5Domain}en/touch/voucher-center/\",\n" +
                "        \"VOUCHER_APPLICABLE_SITE\": \"{h5Domain}en/touch/coupon-applicable-site?orderId={orderId}&certId={certId}\",\n" +
                "        \"OFFER_GLOBAL_HOMEPAGE\": \"{h5Domain}en/touch/offers\",\n" +
                "        \"APP_CONTACT_US_HW\": \"slscheme://app/WebView?url=https://m.shangri-la.com/en/app/contact/huaweiphone.html\",\n" +
                "        \"ROOM_UPGRADE_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/roomupgradetermsconditions.html\",\n" +
                "        \"VOUCHER_HOTEL_SHOP\": \"{h5Domain}en/touch/market-hotel?hotelCode={hotelCode}\",\n" +
                "        \"OFFER_DETAIL\": \"{h5Domain}en/{offerPath}\",\n" +
                "        \"OFFER_HOTEL_HOMEPAGE\": \"{h5Domain}en/touch/{cityAlias}/{hotelAlias}/offers\",\n" +
                "        \"POINTS_TO_MILES\": \"https://m.shangri-la.com/en/touch/point-mile\",\n" +
                "        \"APP_CONTACT_US\": \"slscheme://app/WebView?url=https://m.shangri-la.com/en/app/contact/phone.html\",\n" +
                "        \"COOKIES_POLICY\": \"https://www.shangri-la.com/en/corporate/policies-pledges/app-cookies-policy/?source=APP\",\n" +
                "        \"REDEEM_BOUTIQUE\": \"https://boutique.shangri-la.com/index.php?lang=en&WT.mc_id=SLEB_20230308_MULTI_ORGANICSOCIAL_SLC-APP_ALWAYSON_OTHERS-DISPLAY-COLLECTION_PTS-REDEEM-REFER_EN\",\n" +
                "        \"PRIVACY_POLICY\": \"https://m.shangri-la.com/en/app/policy/appprivacypolicy.html\",\n" +
                "        \"REDEMPTION_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/redemptiontermsconditions.html\",\n" +
                "        \"RESTAURANT_DETAIL\": \"{h5Domain}en/fb/restaurant-detail?restaurantId={restaurantId}\",\n" +
                "        \"BOOKING_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/bookingtermsconditions.html\",\n" +
                "        \"UNROOM_REDEEM\": \"{h5Domain}en/touch/market-points-voucher/\",\n" +
                "        \"WELCOME_AMENITY\": \"{h5Domain}en/touch/welcome-amenities/?type={level}\",\n" +
                "        \"NON_ROOM_AWARDS_TERMS_CONDITIONS\": \"https://m.shangri-la.com/en/app/policy/nonroomawardstermsconditions.html\",\n" +
                "        \"APP_BENEFITS\": \"https://m.shangri-la.com/en/touch/gc/benefits/?type=0\",\n" +
                "        \"VOUCHER_SHOP\": \"{h5Domain}en/touch/market\"";

        Map<String, String> onlineMap = new HashMap<>();
        for (String s : onlineUrlStr.split("\n")) {
            String[] split = s.split(": ");
            onlineMap.put(split[0], split[1]);
        }

        for (Map.Entry<String, String> stringStringEntry : localMap.entrySet()) {
            String key = stringStringEntry.getKey();
            String value = stringStringEntry.getValue();
            String onlineValue = onlineMap.get(key);
            if (!value.equalsIgnoreCase(onlineValue)){
                System.out.println(value);
                System.out.println(onlineValue);
                System.out.println("-----------------------");
            }
        }


    }

    public static class Base{}
    public static class AAA extends Base{}
}
